spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:h2:mem:testdb 
        driverClassName: org.h2.Driver
        username: sgmoomin
        password: 1234
    batch:
        job:
            names: ${job.name:NONE}
            enabled: false
    # quartz:
        # job-store-type: memory